test_arguments:
  unittest_dataset_dir: "unittest_dataset"
  unittest_data: "unittest_data.csv"
  raw_text: "@test_user https://test_link.com Only Processed Text"
  processed_text: "only processed text"
  document: [only, processed, text]